# ################################################### #
# ### RAM VAR generated by RamVarManager 1.0 ### #
# ################################################### #

# Based on TDM4_RX130_ATG485_VARS_LIST_70_24_00.xlsx for PCM5 
 # and on TDM4_RX130_ATG485_VARS_LIST_90_22_00.xlsx for 1UP

# ------------------------------------------------
# Constant Module
# ------------------------------------------------

SW_PACMAN = 1

# ------------------------------------------------
# Function Module
# ------------------------------------------------

if SW_PACMAN:
	VAR = {
		'm_heatsinkTemperature_9_7': {
			'address': 0x0000a2d2,
			'len': 2,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'm_cmpHeatsinkMaxTemp_9_7': {
			'address': 0x0000a2a2,
			'len': 2,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'm_fanHeatsinkMaxTemp_9_7': {
			'address': 0x0000a2a4,
			'len': 2,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'm_cmpHeaterTdTarget_x10Celsius': {
			'address': 0x0000a2a8,
			'len': 2,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'm_cmpHeaterCurrent_8_8_A': {
			'address': 0x0000a2d8,
			'len': 2,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 0   # 0 = Unsigned, 1 = Signed
		},
		'm_hyst_low_refr': {
			'address': 0x0000a2aa,
			'len': 2,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'm_var_low_refr': {
			'address': 0x0000a2ac,
			'len': 2,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'm_exv_max_lowref': {
			'address': 0x00003ca8,
			'len': 4,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'm_Psat_SSTraw_KPa_x100_20_12': {
			'address': 0x00003d0c,
			'len': 4,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'm_pressureDropEst_kPa_x100': {
			'address': 0x00003c80,
			'len': 4,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 0   # 0 = Unsigned, 1 = Signed
		},
		'm_SST_raw_x10Celsius': {
			'address': 0x0000a26c,
			'len': 2,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'm_refrFlow_SSTraw_kg_sec_20_12': {
			'address': 0x00003d14,
			'len': 4,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 0   # 0 = Unsigned, 1 = Signed
		},
		'm_evapInTitle_20_12': {
			'address': 0x00003d04,
			'len': 4,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'm_Tin_EXV_x10Celsius': {
			'address': 0x0000a2c0,
			'len': 2,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'm_rho_20_12': {
			'address': 0x00003c78,
			'len': 4,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 0   # 0 = Unsigned, 1 = Signed
		},
		'm_optimal_rho_20_12': {
			'address': 0x00003c7c,
			'len': 4,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 0   # 0 = Unsigned, 1 = Signed
		},
		'm_SuctionPressureSensEnable': {
			'address': 0x0000a2d4,
			'len': 2,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 0   # 0 = Unsigned, 1 = Signed
		},
		'm_DischargePressureSensEnable': {
			'address': 0x0000a2d6,
			'len': 2,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 0   # 0 = Unsigned, 1 = Signed
		},
		'm_vapSatDensity_Kg_m3_20_12': {
			'address': 0x00003d10,
			'len': 4,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 0   # 0 = Unsigned, 1 = Signed
		},
		'm_exvInEnthalpy_kJ_Kg_x100': {
			'address': 0x00003d08,
			'len': 4,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 0   # 0 = Unsigned, 1 = Signed
		},
		'm_comp_20_12_kg_sec': {
			'address': 0x00003c94,
			'len': 4,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 0   # 0 = Unsigned, 1 = Signed
		},
		'DefrostData.ActivationData.mobileAvgValidDefrostCount': {
			'address': 0x2a56,
			'len': 1,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 0   # 0 = Unsigned, 1 = Signed
		},
		'DefrostData.ActivationData.R_20_12': {
			'address': 0x2a7f,
			'len': 4,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'DefrostData.ActivationData.R_D_20_12': {
			'address': 0x2a87,
			'len': 40,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 1,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'DefrostData.ActivationData.last_R_D_20_12': {
			'address': 0x2aaf,
			'len': 4,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'DefrostData.ActivationData.E_20_12': {
			'address': 0x2ab3,
			'len': 4,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'DefrostData.ActivationData.E_D_20_12': {
			'address': 0x2abb,
			'len': 40,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 1,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'DefrostData.ActivationData.last_E_D_20_12': {
			'address': 0x2ae3,
			'len': 4,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'm_pressureDropEstCoeff_a_FPFormat': {
			'address': 0x2e42,
			'len': 1,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 0   # 0 = Unsigned, 1 = Signed
		},
		'm_pressureDropEstCoeff_a_value': {
			'address': 0x2e43,
			'len': 4,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'm_pressureDropEstCoeff_b_FPFormat': {
			'address': 0x2e47,
			'len': 1,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 0   # 0 = Unsigned, 1 = Signed
		},
		'm_pressureDropEstCoeff_b_value': {
			'address': 0x2e48,
			'len': 4,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'm_pressureDropEstCoeff_c_FPFormat': {
			'address': 0x2e4c,
			'len': 1,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 0   # 0 = Unsigned, 1 = Signed
		},
		'm_pressureDropEstCoeff_c_value': {
			'address': 0x2e4d,
			'len': 4,
			'endian': 0,   # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
	}
else:
	VAR = {
		'm_heatsinkTemperature_9_7': {
			'address': 0x0000a2d0,
			'len': 2,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'm_cmpHeatsinkMaxTemp_9_7': {
			'address': 0x0000a2a0,
			'len': 2,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'm_fanHeatsinkMaxTemp_9_7': {
			'address': 0x0000a2a2,
			'len': 2,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'm_cmpHeaterTdTarget_x10Celsius': {
			'address': 0x0000a2a6,
			'len': 2,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'm_cmpHeaterCurrent_8_8_A': {
			'address': 0x0000a2d6,
			'len': 2,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 0   # 0 = Unsigned, 1 = Signed
		},
		'm_hyst_low_refr': {
			'address': 0x0000a2a8,
			'len': 2,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'm_var_low_refr': {
			'address': 0x0000a2aa,
			'len': 2,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'm_exv_max_lowref': {
			'address': 0x00003ca4,
			'len': 4,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'm_Psat_SSTraw_KPa_x100_20_12': {
			'address': 0x00003d08,
			'len': 4,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'm_pressureDropEst_kPa_x100': {
			'address': 0x00003c7c,
			'len': 4,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 0   # 0 = Unsigned, 1 = Signed
		},
		'm_SST_raw_x10Celsius': {
			'address': 0x0000a26a,
			'len': 2,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'm_refrFlow_SSTraw_kg_sec_20_12': {
			'address': 0x00003d10,
			'len': 4,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 0   # 0 = Unsigned, 1 = Signed
		},
		'm_evapInTitle_20_12': {
			'address': 0x00003d00,
			'len': 4,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'm_Tin_EXV_x10Celsius': {
			'address': 0x0000a2be,
			'len': 2,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'm_rho_20_12': {
			'address': 0x00003c74,
			'len': 4,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 0   # 0 = Unsigned, 1 = Signed
		},
		'm_optimal_rho_20_12': {
			'address': 0x00003c78,
			'len': 4,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 0   # 0 = Unsigned, 1 = Signed
		},
		'm_SuctionPressureSensEnable': {
			'address': 0x0000a2d2,
			'len': 2,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 0   # 0 = Unsigned, 1 = Signed
		},
		'm_DischargePressureSensEnable': {
			'address': 0x0000a2d4,
			'len': 2,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 0   # 0 = Unsigned, 1 = Signed
		},
		'm_vapSatDensity_Kg_m3_20_12': {
			'address': 0x00003d0c,
			'len': 4,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 0   # 0 = Unsigned, 1 = Signed
		},
		'm_exvInEnthalpy_kJ_Kg_x100': {
			'address': 0x00003d04,
			'len': 4,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 0   # 0 = Unsigned, 1 = Signed
		},
		'DefrostData.ActivationData.mobileAvgValidDefrostCount': {
			'address': 0x2a54,
			'len': 1,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 0   # 0 = Unsigned, 1 = Signed
		},
		'DefrostData.ActivationData.R_20_12': {
			'address': 0x2a7d,
			'len': 4,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'DefrostData.ActivationData.R_D_20_12': {
			'address': 0x2a85,
			'len': 40,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 1,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'DefrostData.ActivationData.last_R_D_20_12': {
			'address': 0x2aad,
			'len': 4,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'DefrostData.ActivationData.E_20_12': {
			'address': 0x2ab1,
			'len': 4,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'DefrostData.ActivationData.E_D_20_12': {
			'address': 0x2ab9,
			'len': 40,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 1,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'DefrostData.ActivationData.last_E_D_20_12': {
			'address': 0x2ae1,
			'len': 4,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'm_pressureDropEstCoeff_a_FPFormat': {
			'address': 0x2e40,
			'len': 1,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 0   # 0 = Unsigned, 1 = Signed
		},
		'm_pressureDropEstCoeff_a_value': {
			'address': 0x2e41,
			'len': 4,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'm_pressureDropEstCoeff_b_FPFormat': {
			'address': 0x2e45,
			'len': 1,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 0   # 0 = Unsigned, 1 = Signed
		},
		'm_pressureDropEstCoeff_b_value': {
			'address': 0x2e46,
			'len': 4,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
		'm_pressureDropEstCoeff_c_FPFormat': {
			'address': 0x2e4a,
			'len': 1,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 0   # 0 = Unsigned, 1 = Signed
		},
		'm_pressureDropEstCoeff_c_value': {
			'address': 0x2e4b,
			'len': 4,
			'endian': 0,    # 0 = Little, 1 = Big
			'format': 0,   # 0 = Scalar, 1 = Array
			'signed': 1   # 0 = Unsigned, 1 = Signed
		},
	}
